name: lunart_workspace
description: An ergonomic server side ecosystem
version: 0.0.1

environment:
  sdk: ^3.7.2

workspace:
  - libs/lunart
  - libs/lunart_core
  - libs/lunart_express
  - libs/playground
  - examples/basic
